### ISSUE TITLE
issues with new node version node/4.1.1

### ISSUE THREAD

**Issue by fvanzile** [kayomarz/dynamodb-data-types#4]
it looks like node/4.1.1 deprecated a lot of the util functions because they no longer work and dynamodb-data-types is using these util functions.  so the data mapping are not correct anymore.
is someone working on this yet?

**Comment by kayomarz** [comment]
Thanks for pointing it out - there's no one working on it yet.

**Comment by kayomarz** [comment]
>  so the data mapping are not correct anymore.

@fvanzile Node's deprecation does not break the functionality in dynmanodb-data-types. Are you facing any issues?

Currently, dynamodb-data-types makes use of `util.isArray()` which has now deprecated.

I'll work on this.

**Comment by fvanzile** [comment]
it looks like they deprecated them because they on longer work and they did not want to fix them.

http://stackoverflow.com/questions/32515413/why-have-many-util-is-functions-been-deprecated-in-node-js-v4-0-0

i am getting type differences on arrays and binary arrays between node 1.2.X and 4.X.  

thank you for your help.

Frank

**Comment by kayomarz** [comment]
@fvanzile I've removed use of the deprecated function. The update has been published to dynamodb-data-types version2.1.1.  Sorry for the delay in getting back to you.
