### ISSUE TITLE
Ignore/Skip functionality

### ISSUE THREAD

**Issue by kzimnicki** [kayomarz/dynamodb-data-types#5]
Is it possible to add functionality for ignored fields ?

```javascript
{
   id: 'abc',
   $ignoredField: 'abc'
}
```

So at the end only "id" key will be converted.

**Comment by kayomarz** [comment]
It might be better to leave such functionality to npm modules such as `lodash` or `underscore`.

For Example:

    var _ = require('lodash');
    var obj = {id: 'abc', $ignoredField: 'abc'}
    var obj2 = _.omit(obj, '$ignoredField');
    // obj2 => {id: 'abc'}

Does this solve what you need?
