### ISSUE TITLE
Would this work in the browser?

### ISSUE THREAD

**Issue by mw44118** [kayomarz/dynamodb-data-types#6]
I need something like this, but I'm just using browser JS, not node.

**Comment by kayomarz** [comment]
It won't work in the browser. It was built for Node before Amazon released its SDK for the browser.

However, most of the library including the core is written in simple JavaScript which will work in the browser. The few required changes which I can think of are mentioned in [platform notes](https://github.com/kayomarz/dynamodb-data-types#platform).

**Comment by mw44118** [comment]
Thanks for the reply!

As far as I can tell, the Amazon SDK for the browser doesn't offer any way to load or dump data structures with the right type annotations, so this library might be really helpful.

I'll get back to you with how it goes.

**Comment by kayomarz** [comment]
I took a look at the code - It should be easy to make it work for the browser. 

I'll give it a try this weekend.

**Comment by mw44118** [comment]
Thanks so much!

One problem that we ran into already is that we got some cycles in our
objects.  I need to figure out how to copy my objects and then walk through
the copies and filter out certain attributes.  I could do this with my eyes
closed in python, but I don't know how to do this introspection stuff with
JS.

**Comment by kayomarz** [comment]
No problem.

Regarding cyclic objects this code might be of interest to you: https://github.com/douglascrockford/JSON-js/blob/master/cycle.js

**Comment by kayomarz** [comment]
@mw44118 added build for use in the browser.

See https://github.com/kayomarz/dynamodb-data-types#use-in-the-browser-with-aws-sdk-for-javascript-in-the-browser

Also see https://github.com/kayomarz/dynamodb-data-types#use-in-the-browser
