### ISSUE TITLE
Browser build without Buffer

### ISSUE THREAD

**Issue by breandr** [kayomarz/dynamodb-data-types#9]
Any chance of building a version for the browser that does not include support for Buffer?

**Comment by kayomarz** [comment]
@breandr You can now [try the browser version](https://github.com/kayomarz/dynamodb-data-types/blob/master/dist) without `Buffer`.

Version `3.0.0` onwards, browser builds in [/dist](https://github.com/kayomarz/dynamodb-data-types/blob/master/dist) are without `Buffer`. Filesize of `dynamodb-data-types.min.js` has reduced from `40K` to `6.5K`.

The older browser distribution with Browserify's `Buffer` shim, will be available in [/dist-with-buffer](https://github.com/kayomarz/dynamodb-data-types/tree/master/dist-with-buffer)

Node.js users are not affected by this change.

**Comment by breandr** [comment]
That's awesome! Thanks!
